C4Context
    accTitle: Expert nutritionist system
    accDescr: Containers

    Person(person, "User", "A user who needs nutrition recommendations")

    System_Boundary(webApp, "Nutrition Application", "Allows users to get nutrition recommendations and recognize additives in the product composition") {
        Container(webApp, "Mobile Application", "Swift", "App for getting recommendations")
        Container(api, "API Application", "API Gateway", "API that manages product details")

        Container(kafka, "Kafka", "Kafka", "Message broker")
        Container(spark, "Spark", "Spark", "Data processing and model training")
        ContainerDb(db, "Hadoop", "HDFS", "Tables to store users data")

        Rel(webApp, api, "Makes calls to", "JSON-RPC")
        Rel(api, db, "Reads and writes to", "HDFS")

        Rel(api, kafka, "Write to", "Kafka")
        Rel(spark, kafka, "Reads from", "Kafka")
        Rel(spark, db, "Reads and writes to", "Spark")
    }

    Rel(person, webApp, "Visits", "JSON-RPC")
