C4Context
    accTitle: News Feed System
    accDescr: Context

    Person(person, "User", "User who is reading news")

    System_Ext(mobileApp, "Mobile Application", "Allows users to view and interact with articles and news feed")
    System(nfs, "News Feed System", "Compiles a news feed")
    System_Ext(dwh, "Data Warehouse", "Stores data")

    Rel(person, mobileApp, "View and interact with news")
    Rel(mobileApp, nfs, "Gets news feed for user")
    Rel(nfs, dwh, "Retrieves recommendations")
    Rel(mobileApp, dwh, "Saves user events")
