C4Context
    accTitle: Online movie theater System
    accDescr: Containers

    Person(user, "User", "Online movie theater user")

    System_Boundary(webApp, "Online movie theater", "Allows users to scroll their feed, view and interact with films") {
        Container(webApp, "Web Application", "HTML", "Web frontend for using service")
        Container(api, "API Application", "API Gateway", "API that manages product details")
        Container(kafka, "Kafka", "Kafka", "Broker")
        Container(spark, "Spark", "Spark", "Data processing")
        ContainerDb(hdfs, "Distributed Database", "HDFS", "Tables to store users interactions and recommendations")
        ContainerDb(rmc, "Recommendations Database", "MemcachedDB", "Tables to store users recommendations for feed")
        ContainerDb(fmc, "Films Data Database", "MemcachedDB", "Tables to store films data")
        Rel(webApp, api, "Makes calls to", "JSON-RPC")
        Rel(api, rmc, "Reads from", "JSON-RPC")
        Rel(api, fmc, "Reads from", "JSON-RPC")
        Rel(api, kafka, "Writes to", "JSON-RPC")
        Rel(spark, kafka, "Reads from", "JSON-RPC")
        Rel(spark, hdfs, "Reads and writes to", "JSON-RPC")
        Rel(spark, rmc, "Writes to", "JSON-RPC")
    }

    Rel(user, webApp, "Visits", "JSON-RPC")
