C4Context
    accTitle: AI DJ
    accDescr: Containers

    Person(person, "User", "User who needs to generate a playlist")
    Rel(person, webApp, "Visits", "JSON-RPC")

    System_Boundary(webApp, "Shop", "Allows customers to search, view and purchase products") {
        Container(webApp, "Web Application", "react", "Web frontend for prompting and viewing recos")
        Container(api, "API Application", "API Gateway", "API that manages prompt processing and reco generation")

        Rel(api, mlSer, "Makes calls to", "JSON/HTTP")
        Rel(webApp, api, "Makes calls to", "JSON/HTTP")
    }

    System_Boundary(mlSer, "Reco Service", "Generate song recos based on DL models extracted features") {
        Container(mlSer, "Inference API", "API Gateway", "ML models inference API")
        Container(kafka, "Kafka", "", "Tasks and queues distribution")
        Container(db, "Hadoop", "", "Big Data storage and processing")

        Rel(mlSer, kafka, "Get songs features", "")
        Rel(kafka, db, "Get songs data", "")

    }

    System_Ext(ymusic, "Yandex Music", "Musical service")
    System_Ext(tunebat, "Tunebat.com", "Musical harmonic data")
    Container(parser, "Parser", "", "Music web services parser")

    Rel(ymusic, parser, "Parse playlist data", "")
    Rel(tunebat, parser, "Get properties for parsed songs", "")

    Rel(parser, db, "Pass songs data", "")


