mindmap
  root((Агрегатор мероприятий MorePost))
    Бизнес-цель
      Персонализированные подборки мероприятий
    ML Задачи
      Классификация постов
      Суммаризация текста
      Тематика мероприятия
    Источники данных
      Социальные сети
        Вконтакте
        Telegram
    Технологии
      Сбор данных
        Python парсеры
      Обработка данных
        Apache Hadoop
          HDFS
          Spark
          YARN
      Хранение данных
        Обработанные данные
          PostgreSQL
        Данные для обучения
          HDFS
      Транспорт
        Kafka
    Выходные данные
      Персональные дайджесты
    Интерфейсы
      REST API
        FastAPI
      Телеграм-бот
        AsyncTeleBot
      Мобильное приложение
        Flutter