flowchart TD
    A[Пользователь сервиса] --> B(Сервис)
    B[Сервис] --> C(Текстовый запрос в чате)
    B[Сервис] --> D(Отправка изображения)
    C[Текстовый запрос в чате] --> E(Получить рекомендации по питанию)
    D[Отправка изображения] --> F(Анализ добавок в составе продукта)
